### ISSUE TITLE
系统报502错误

### ISSUE THREAD

**Issue by admin-del** [Autumn-27/ScopeSentry#14]
![Snipaste_2024-06-16_11-52-30](https://github.com/Autumn-27/ScopeSentry/assets/105182827/57b51274-1585-483a-99dc-8c5a8c744ad5)

**Comment by Autumn-27** [comment]
> ![Snipaste_2024-06-16_11-52-30](https://private-user-images.githubusercontent.com/105182827/340063495-57b51274-1585-483a-99dc-8c5a8c744ad5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MTg0NzgsIm5iZiI6MTcxODUxODE3OCwicGF0aCI6Ii8xMDUxODI4MjcvMzQwMDYzNDk1LTU3YjUxMjc0LTE1ODUtNDgzYS05OWRjLThjNWE4Yzc0NGFkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQwNjA5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmFiODQzN2I4MjhhYzNkNTA2YmI2MjAwMmNhZjZkYmExMDBmNTYyMjYxNzViZTk4NzgzNThjZjFmOTQ0ZTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.otIvVVV3mnWUTGZiUdhy4Upen06VQa0q9LGE3tcNYNc)

看下服务端日志

**Comment by admin-del** [comment]
2024-06-16 11:23:27 INFO:     Will watch for changes in these directories: ['/opt/ScopeSentry']
2024-06-16 11:23:27 INFO:     Uvicorn running on http://0.0.0.0:8082 (Press CTRL+C to quit)
2024-06-16 11:23:27 INFO:     Started reloader process [26] using WatchFiles
2024-06-16 11:23:28 INFO:     Started server process [44]
2024-06-16 11:23:28 INFO:     Waiting for application startup.
2024-06-16 11:23:30 2024-06-16 11:23:30.061 | ERROR    | core.db:create_database:145 - Error creating database: scopesentry-mongodb:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 2.0s, Topology Description: <TopologyDescription id: 666e5ab097bfb4e24ea61cad, topology_type: Unknown, servers: [<ServerDescription ('scopesentry-mongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('scopesentry-mongodb:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2024-06-16 11:23:30 ERROR:    Traceback (most recent call last):
2024-06-16 11:23:30   File "/opt/ScopeSentry/core/db.py", line 32, in create_database
2024-06-16 11:23:30     database_names = await client.list_database_names()
2024-06-16 11:23:30   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
2024-06-16 11:23:30     result = self.fn(*self.args, **self.kwargs)
2024-06-16 11:23:30   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1952, in list_database_names
2024-06-16 11:23:30     return [doc["name"] for doc in self.list_databases(session, nameOnly=True, comment=comment)]
2024-06-16 11:23:30   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1925, in list_databases
2024-06-16 11:23:30     res = admin._retryable_read_command(cmd, session=session)
2024-06-16 11:23:30   File "/usr/local/lib/python3.7/site-packages/pymongo/database.py", line 1026, in _retryable_read_command
2024-06-16 11:23:30     return self.__client._retryable_read(_cmd, read_preference, session)
2024-06-16 11:23:30   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1499, in _retryable_read
2024-06-16 11:23:30     retryable=retryable,
2024-06-16 11:23:30   File "/usr/local/lib/python3.7/site-packages/pymongo/_csot.py", line 107, in csot_wrapper
2024-06-16 11:23:30     return func(self, *args, **kwargs)
2024-06-16 11:23:30   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1461, in _retry_internal
2024-06-16 11:23:30     retryable=retryable,
2024-06-16 11:23:30   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 2315, in run
2024-06-16 11:23:30     return self._read() if self._is_read else self._write()
2024-06-16 11:23:30   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 2437, in _read
2024-06-16 11:23:30     self._server = self._get_server()
2024-06-16 11:23:30   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 2401, in _get_server
2024-06-16 11:23:30     self._server_selector, self._session, address=self._address
2024-06-16 11:23:30   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1303, in _select_server
2024-06-16 11:23:26 Starting nginx: nginx.
2024-06-16 11:23:27    _____                         _____            _              
2024-06-16 11:23:27   / ____|                       / ____|          | |             
2024-06-16 11:23:27  | (___   ___ ___  _ __   ___  | (___   ___ _ __ | |_ _ __ _   _ 
2024-06-16 11:23:27   \___ \ / __/ _ \| '_ \ / _ \  \___ \ / _ \ '_ \| __| '__| | | |
2024-06-16 11:23:27   ____) | (_| (_) | |_) |  __/  ____) |  __/ | | | |_| |  | |_| |
2024-06-16 11:23:27  |_____/ \___\___/| .__/ \___| |_____/ \___|_| |_|\__|_|   \__, |
2024-06-16 11:23:27                   | |                                       __/ |
2024-06-16 11:23:27                   |_|                                      |___/ 
2024-06-16 11:29:15 Starting nginx: nginx.
2024-06-16 11:29:16    _____                         _____            _              
2024-06-16 11:29:16   / ____|                       / ____|          | |             
2024-06-16 11:29:16  | (___   ___ ___  _ __   ___  | (___   ___ _ __ | |_ _ __ _   _ 
2024-06-16 11:29:16   \___ \ / __/ _ \| '_ \ / _ \  \___ \ / _ \ '_ \| __| '__| | | |
2024-06-16 11:29:16   ____) | (_| (_) | |_) |  __/  ____) |  __/ | | | |_| |  | |_| |
2024-06-16 11:29:16  |_____/ \___\___/| .__/ \___| |_____/ \___|_| |_|\__|_|   \__, |
2024-06-16 11:29:16                   | |                                       __/ |
2024-06-16 11:29:16                   |_|                                      |___/ 
2024-06-16 11:50:41 Starting nginx: nginx.
2024-06-16 11:50:42    _____                         _____            _              
2024-06-16 11:50:42   / ____|                       / ____|          | |             
2024-06-16 11:50:42  | (___   ___ ___  _ __   ___  | (___   ___ _ __ | |_ _ __ _   _ 
2024-06-16 11:50:42   \___ \ / __/ _ \| '_ \ / _ \  \___ \ / _ \ '_ \| __| '__| | | |
2024-06-16 11:50:42   ____) | (_| (_) | |_) |  __/  ____) |  __/ | | | |_| |  | |_| |
2024-06-16 11:50:42  |_____/ \___\___/| .__/ \___| |_____/ \___|_| |_|\__|_|   \__, |
2024-06-16 11:50:42                   | |                                       __/ |
2024-06-16 11:50:42                   |_|                                      |___/ 
2024-06-16 11:23:30     server = topology.select_server(server_selector)
2024-06-16 11:23:30   File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 302, in select_server
2024-06-16 11:23:30     server = self._select_server(selector, server_selection_timeout, address)
2024-06-16 11:23:30   File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 286, in _select_server
2024-06-16 11:23:30     servers = self.select_servers(selector, server_selection_timeout, address)
2024-06-16 11:23:30   File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 237, in select_servers
2024-06-16 11:23:30     server_descriptions = self._select_servers_loop(selector, server_timeout, address)
2024-06-16 11:23:30   File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 260, in _select_servers_loop
2024-06-16 11:23:30     f"{self._error_message(selector)}, Timeout: {timeout}s, Topology Description: {self.description!r}"
2024-06-16 11:23:30 pymongo.errors.ServerSelectionTimeoutError: scopesentry-mongodb:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 2.0s, Topology Description: <TopologyDescription id: 666e5ab097bfb4e24ea61cad, topology_type: Unknown, servers: [<ServerDescription ('scopesentry-mongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('scopesentry-mongodb:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2024-06-16 11:23:30 
2024-06-16 11:23:30 During handling of the above exception, another exception occurred:
2024-06-16 11:23:30 
2024-06-16 11:23:30 Traceback (most recent call last):
2024-06-16 11:23:30   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 677, in lifespan
2024-06-16 11:23:30     async with self.lifespan_context(app) as maybe_state:
2024-06-16 11:23:30   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 566, in __aenter__
2024-06-16 11:23:30     await self._router.startup()
2024-06-16 11:23:30   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 654, in startup
2024-06-16 11:23:30     await handler()
2024-06-16 11:23:30   File "/opt/ScopeSentry/main.py", line 32, in startup_db_client
2024-06-16 11:23:30     await db.create_database()
2024-06-16 11:23:30   File "/opt/ScopeSentry/core/db.py", line 146, in create_database
2024-06-16 11:23:30     exit(0)
2024-06-16 11:23:30   File "/usr/local/lib/python3.7/_sitebuiltins.py", line 26, in __call__
2024-06-16 11:23:30     raise SystemExit(code)
2024-06-16 11:23:30 SystemExit: 0
2024-06-16 11:23:30 
2024-06-16 11:23:30 ERROR:    Application startup failed. Exiting.
2024-06-16 11:29:16 INFO:     Will watch for changes in these directories: ['/opt/ScopeSentry']
2024-06-16 11:29:16 INFO:     Uvicorn running on http://0.0.0.0:8082 (Press CTRL+C to quit)
2024-06-16 11:29:16 INFO:     Started reloader process [25] using WatchFiles
2024-06-16 11:29:17 INFO:     Started server process [44]
2024-06-16 11:29:17 INFO:     Waiting for application startup.
2024-06-16 11:29:19 2024-06-16 11:29:19.791 | ERROR    | core.db:create_database:145 - Error creating database: scopesentry-mongodb:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 2.0s, Topology Description: <TopologyDescription id: 666e5c0d50c954238e28486d, topology_type: Unknown, servers: [<ServerDescription ('scopesentry-mongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('scopesentry-mongodb:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2024-06-16 11:29:19 ERROR:    Traceback (most recent call last):
2024-06-16 11:29:19   File "/opt/ScopeSentry/core/db.py", line 32, in create_database
2024-06-16 11:29:19     database_names = await client.list_database_names()
2024-06-16 11:29:19   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
2024-06-16 11:29:19     result = self.fn(*self.args, **self.kwargs)
2024-06-16 11:29:19   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1952, in list_database_names
2024-06-16 11:29:19     return [doc["name"] for doc in self.list_databases(session, nameOnly=True, comment=comment)]
2024-06-16 11:29:19   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1925, in list_databases
2024-06-16 11:29:19     res = admin._retryable_read_command(cmd, session=session)
2024-06-16 11:29:19   File "/usr/local/lib/python3.7/site-packages/pymongo/database.py", line 1026, in _retryable_read_command
2024-06-16 11:29:19     return self.__client._retryable_read(_cmd, read_preference, session)
2024-06-16 11:29:19   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1499, in _retryable_read
2024-06-16 11:29:19     retryable=retryable,
2024-06-16 11:29:19   File "/usr/local/lib/python3.7/site-packages/pymongo/_csot.py", line 107, in csot_wrapper
2024-06-16 11:29:19     return func(self, *args, **kwargs)
2024-06-16 11:29:19   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1461, in _retry_internal
2024-06-16 11:29:19     retryable=retryable,
2024-06-16 11:29:19   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 2315, in run
2024-06-16 11:29:19     return self._read() if self._is_read else self._write()
2024-06-16 11:29:19   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 2437, in _read
2024-06-16 11:29:19     self._server = self._get_server()
2024-06-16 11:29:19   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 2401, in _get_server
2024-06-16 11:29:19     self._server_selector, self._session, address=self._address
2024-06-16 11:29:19   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1303, in _select_server
2024-06-16 11:29:19     server = topology.select_server(server_selector)
2024-06-16 11:29:19   File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 302, in select_server
2024-06-16 11:29:19     server = self._select_server(selector, server_selection_timeout, address)
2024-06-16 11:29:19   File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 286, in _select_server
2024-06-16 11:29:19     servers = self.select_servers(selector, server_selection_timeout, address)
2024-06-16 11:29:19   File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 237, in select_servers
2024-06-16 11:29:19     server_descriptions = self._select_servers_loop(selector, server_timeout, address)
2024-06-16 11:29:19   File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 260, in _select_servers_loop
2024-06-16 11:29:19     f"{self._error_message(selector)}, Timeout: {timeout}s, Topology Description: {self.description!r}"
2024-06-16 11:29:19 pymongo.errors.ServerSelectionTimeoutError: scopesentry-mongodb:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 2.0s, Topology Description: <TopologyDescription id: 666e5c0d50c954238e28486d, topology_type: Unknown, servers: [<ServerDescription ('scopesentry-mongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('scopesentry-mongodb:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2024-06-16 11:29:19 
2024-06-16 11:29:19 During handling of the above exception, another exception occurred:
2024-06-16 11:29:19 
2024-06-16 11:29:19 Traceback (most recent call last):
2024-06-16 11:29:19   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 677, in lifespan
2024-06-16 11:29:19     async with self.lifespan_context(app) as maybe_state:
2024-06-16 11:29:19   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 566, in __aenter__
2024-06-16 11:29:19     await self._router.startup()
2024-06-16 11:29:19   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 654, in startup
2024-06-16 11:29:19     await handler()
2024-06-16 11:29:19   File "/opt/ScopeSentry/main.py", line 32, in startup_db_client
2024-06-16 11:29:19     await db.create_database()
2024-06-16 11:29:19   File "/opt/ScopeSentry/core/db.py", line 146, in create_database
2024-06-16 11:29:19     exit(0)
2024-06-16 11:29:19   File "/usr/local/lib/python3.7/_sitebuiltins.py", line 26, in __call__
2024-06-16 11:29:19     raise SystemExit(code)
2024-06-16 11:29:19 SystemExit: 0
2024-06-16 11:29:19 
2024-06-16 11:29:19 ERROR:    Application startup failed. Exiting.
2024-06-16 11:50:42 INFO:     Will watch for changes in these directories: ['/opt/ScopeSentry']
2024-06-16 11:50:42 INFO:     Uvicorn running on http://0.0.0.0:8082 (Press CTRL+C to quit)
2024-06-16 11:50:42 INFO:     Started reloader process [26] using WatchFiles
2024-06-16 11:50:43 INFO:     Started server process [44]
2024-06-16 11:50:43 INFO:     Waiting for application startup.
2024-06-16 11:50:45 2024-06-16 11:50:45.771 | ERROR    | core.db:create_database:145 - Error creating database: scopesentry-mongodb:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 2.0s, Topology Description: <TopologyDescription id: 666e6113093f43b4d81f5d21, topology_type: Unknown, servers: [<ServerDescription ('scopesentry-mongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('scopesentry-mongodb:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2024-06-16 11:50:45 ERROR:    Traceback (most recent call last):
2024-06-16 11:50:45   File "/opt/ScopeSentry/core/db.py", line 32, in create_database
2024-06-16 11:50:45     database_names = await client.list_database_names()
2024-06-16 11:50:45   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
2024-06-16 11:50:45     result = self.fn(*self.args, **self.kwargs)
2024-06-16 11:50:45   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1952, in list_database_names
2024-06-16 11:50:45     return [doc["name"] for doc in self.list_databases(session, nameOnly=True, comment=comment)]
2024-06-16 11:50:45   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1925, in list_databases
2024-06-16 11:50:45     res = admin._retryable_read_command(cmd, session=session)
2024-06-16 11:50:45   File "/usr/local/lib/python3.7/site-packages/pymongo/database.py", line 1026, in _retryable_read_command
2024-06-16 11:50:45     return self.__client._retryable_read(_cmd, read_preference, session)
2024-06-16 11:50:45   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1499, in _retryable_read
2024-06-16 11:50:45     retryable=retryable,
2024-06-16 11:50:45   File "/usr/local/lib/python3.7/site-packages/pymongo/_csot.py", line 107, in csot_wrapper
2024-06-16 11:50:45     return func(self, *args, **kwargs)
2024-06-16 11:50:45   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1461, in _retry_internal
2024-06-16 11:50:45     retryable=retryable,
2024-06-16 11:50:45   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 2315, in run
2024-06-16 11:50:45     return self._read() if self._is_read else self._write()
2024-06-16 11:50:45   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 2437, in _read
2024-06-16 11:50:45     self._server = self._get_server()
2024-06-16 11:50:45   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 2401, in _get_server
2024-06-16 11:50:45     self._server_selector, self._session, address=self._address
2024-06-16 11:50:45   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1303, in _select_server
2024-06-16 11:50:45     server = topology.select_server(server_selector)
2024-06-16 11:50:45   File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 302, in select_server
2024-06-16 11:50:45     server = self._select_server(selector, server_selection_timeout, address)
2024-06-16 11:50:45   File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 286, in _select_server
2024-06-16 11:50:45     servers = self.select_servers(selector, server_selection_timeout, address)
2024-06-16 11:50:45   File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 237, in select_servers
2024-06-16 11:50:45     server_descriptions = self._select_servers_loop(selector, server_timeout, address)
2024-06-16 11:50:45   File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 260, in _select_servers_loop
2024-06-16 11:50:45     f"{self._error_message(selector)}, Timeout: {timeout}s, Topology Description: {self.description!r}"
2024-06-16 11:50:45 pymongo.errors.ServerSelectionTimeoutError: scopesentry-mongodb:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 2.0s, Topology Description: <TopologyDescription id: 666e6113093f43b4d81f5d21, topology_type: Unknown, servers: [<ServerDescription ('scopesentry-mongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('scopesentry-mongodb:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2024-06-16 11:50:45 
2024-06-16 11:50:45 During handling of the above exception, another exception occurred:
2024-06-16 11:50:45 
2024-06-16 11:50:45 Traceback (most recent call last):
2024-06-16 11:50:45   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 677, in lifespan
2024-06-16 11:50:45     async with self.lifespan_context(app) as maybe_state:
2024-06-16 11:50:45   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 566, in __aenter__
2024-06-16 11:50:45     await self._router.startup()
2024-06-16 11:50:45   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 654, in startup
2024-06-16 11:50:45     await handler()
2024-06-16 11:50:45   File "/opt/ScopeSentry/main.py", line 32, in startup_db_client
2024-06-16 11:50:45     await db.create_database()
2024-06-16 11:50:45   File "/opt/ScopeSentry/core/db.py", line 146, in create_database
2024-06-16 11:50:45     exit(0)
2024-06-16 11:50:45   File "/usr/local/lib/python3.7/_sitebuiltins.py", line 26, in __call__
2024-06-16 11:50:45     raise SystemExit(code)
2024-06-16 11:50:45 SystemExit: 0
2024-06-16 11:50:45 
2024-06-16 11:50:45 ERROR:    Application startup failed. Exiting.
2024-06-16 11:51:07 INFO:     Will watch for changes in these directories: ['/opt/ScopeSentry']
2024-06-16 11:51:07 INFO:     Uvicorn running on http://0.0.0.0:8082 (Press CTRL+C to quit)
2024-06-16 11:51:07 INFO:     Started reloader process [26] using WatchFiles
2024-06-16 11:51:07 INFO:     Started server process [45]
2024-06-16 11:51:07 INFO:     Waiting for application startup.
2024-06-16 11:52:07 2024-06-16 11:52:07.661 | ERROR    | core.db:create_database:145 - Error creating database: interrupted at shutdown, full error: {'ok': 0.0, 'errmsg': 'interrupted at shutdown', 'code': 11600, 'codeName': 'InterruptedAtShutdown'}
2024-06-16 11:52:07 ERROR:    Traceback (most recent call last):
2024-06-16 11:52:07   File "/opt/ScopeSentry/core/db.py", line 128, in create_database
2024-06-16 11:52:07     await collection.insert_one(default_rule)
2024-06-16 11:52:07   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
2024-06-16 11:52:07     result = self.fn(*self.args, **self.kwargs)
2024-06-16 11:52:07   File "/usr/local/lib/python3.7/site-packages/pymongo/collection.py", line 676, in insert_one
2024-06-16 11:52:07     comment=comment,
2024-06-16 11:52:07   File "/usr/local/lib/python3.7/site-packages/pymongo/collection.py", line 609, in _insert_one
2024-06-16 11:52:07     self.__database.client._retryable_write(acknowledged, _insert_command, session)
2024-06-16 11:52:07   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1523, in _retryable_write
2024-06-16 11:52:07     return self._retry_with_session(retryable, func, s, bulk)
2024-06-16 11:52:07   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1425, in _retry_with_session
2024-06-16 11:52:07     retryable=retryable,
2024-06-16 11:52:07   File "/usr/local/lib/python3.7/site-packages/pymongo/_csot.py", line 107, in csot_wrapper
2024-06-16 11:52:07     return func(self, *args, **kwargs)
2024-06-16 11:52:07   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1461, in _retry_internal
2024-06-16 11:52:07     retryable=retryable,
2024-06-16 11:52:07   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 2315, in run
2024-06-16 11:52:07     return self._read() if self._is_read else self._write()
2024-06-16 11:52:07   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 2423, in _write
2024-06-16 11:52:07     return self._func(self._session, conn, self._retryable)  # type: ignore
2024-06-16 11:52:07   File "/usr/local/lib/python3.7/site-packages/pymongo/collection.py", line 604, in _insert_command
2024-06-16 11:52:07     retryable_write=retryable_write,
2024-06-16 11:52:07   File "/usr/local/lib/python3.7/site-packages/pymongo/helpers.py", line 322, in inner
2024-06-16 11:52:07     return func(*args, **kwargs)
2024-06-16 11:52:07   File "/usr/local/lib/python3.7/site-packages/pymongo/pool.py", line 990, in command
2024-06-16 11:52:07     write_concern=write_concern,
2024-06-16 11:52:07   File "/usr/local/lib/python3.7/site-packages/pymongo/network.py", line 196, in command
2024-06-16 11:52:07     parse_write_concern_error=parse_write_concern_error,
2024-06-16 11:52:07   File "/usr/local/lib/python3.7/site-packages/pymongo/helpers.py", line 217, in _check_command_response
2024-06-16 11:52:07     raise NotPrimaryError(errmsg, response)
2024-06-16 11:52:07 pymongo.errors.NotPrimaryError: interrupted at shutdown, full error: {'ok': 0.0, 'errmsg': 'interrupted at shutdown', 'code': 11600, 'codeName': 'InterruptedAtShutdown'}
2024-06-16 11:52:07 
2024-06-16 11:52:07 During handling of the above exception, another exception occurred:
2024-06-16 11:52:07 
2024-06-16 11:52:07 Traceback (most recent call last):
2024-06-16 11:52:07   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 677, in lifespan
2024-06-16 11:52:07     async with self.lifespan_context(app) as maybe_state:
2024-06-16 11:52:07   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 566, in __aenter__
2024-06-16 11:52:07     await self._router.startup()
2024-06-16 11:52:07   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 654, in startup
2024-06-16 11:52:07     await handler()
2024-06-16 11:52:07   File "/opt/ScopeSentry/main.py", line 32, in startup_db_client
2024-06-16 11:52:07     await db.create_database()
2024-06-16 11:52:07   File "/opt/ScopeSentry/core/db.py", line 146, in create_database
2024-06-16 11:52:07     exit(0)
2024-06-16 11:52:07   File "/usr/local/lib/python3.7/_sitebuiltins.py", line 26, in __call__
2024-06-16 11:52:07     raise SystemExit(code)
2024-06-16 11:52:07 SystemExit: 0
2024-06-16 11:52:07 
2024-06-16 11:52:07 ERROR:    Application startup failed. Exiting.
2024-06-16 11:51:06 Starting nginx: nginx.
2024-06-16 11:51:07    _____                         _____            _              
2024-06-16 11:51:07   / ____|                       / ____|          | |             
2024-06-16 11:51:07  | (___   ___ ___  _ __   ___  | (___   ___ _ __ | |_ _ __ _   _ 
2024-06-16 11:51:07   \___ \ / __/ _ \| '_ \ / _ \  \___ \ / _ \ '_ \| __| '__| | | |
2024-06-16 11:51:07   ____) | (_| (_) | |_) |  __/  ____) |  __/ | | | |_| |  | |_| |
2024-06-16 11:51:07  |_____/ \___\___/| .__/ \___| |_____/ \___|_| |_|\__|_|   \__, |
2024-06-16 11:51:07                   | |                                       __/ |
2024-06-16 11:51:07                   |_|                                      |___/
