### ISSUE TITLE
单机部署scope-sentry启动失败警告

### ISSUE THREAD

**Issue by qzinori** [Autumn-27/ScopeSentry#33]
2024-07-05 11:07:07.694 | ERROR    | core.db:create_database:155 - Error creating database: No servers found yet, Timeout: 2.0s, Topology Description: <TopologyDescription id: 66876359636455f3558eae8d, topology_type: Unknown, servers: [<ServerDescription ('scopesentry-mongodb', 27017) server_type: Unknown, rtt: None>]>
ERROR:    Traceback (most recent call last):
  File "/opt/ScopeSentry/core/db.py", line 42, in create_database
    database_names = await client.list_database_names()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1952, in list_database_names
    return [doc["name"] for doc in self.list_databases(session, nameOnly=True, comment=comment)]
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1925, in list_databases
    res = admin._retryable_read_command(cmd, session=session)
  File "/usr/local/lib/python3.7/site-packages/pymongo/database.py", line 1026, in _retryable_read_command
    return self.__client._retryable_read(_cmd, read_preference, session)
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1499, in _retryable_read
    retryable=retryable,
  File "/usr/local/lib/python3.7/site-packages/pymongo/_csot.py", line 107, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1461, in _retry_internal
    retryable=retryable,
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 2315, in run
    return self._read() if self._is_read else self._write()
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 2437, in _read
    self._server = self._get_server()
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 2401, in _get_server
    self._server_selector, self._session, address=self._address
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1303, in _select_server
    server = topology.select_server(server_selector)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 302, in select_server
    server = self._select_server(selector, server_selection_timeout, address)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 286, in _select_server
    servers = self.select_servers(selector, server_selection_timeout, address)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 237, in select_servers
    server_descriptions = self._select_servers_loop(selector, server_timeout, address)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 260, in _select_servers_loop
    f"{self._error_message(selector)}, Timeout: {timeout}s, Topology Description: {self.description!r}"
pymongo.errors.ServerSelectionTimeoutError: No servers found yet, Timeout: 2.0s, Topology Description: <TopologyDescription id: 66876359636455f3558eae8d, topology_type: Unknown, servers: [<ServerDescription ('scopesentry-mongodb', 27017) server_type: Unknown, rtt: None>]>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/opt/ScopeSentry/main.py", line 57, in startup_db_client
    await db.create_database()
  File "/opt/ScopeSentry/core/db.py", line 156, in create_database
    exit(0)
  File "/usr/local/lib/python3.7/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0

ERROR:    Application startup failed. Exiting.
Starting nginx: nginx.
INFO:     Will watch for changes in these directories: ['/opt/ScopeSentry']
   _____                         _____            _
  / ____|                       / ____|          | |
 | (___   ___ ___  _ __   ___  | (___   ___ _ __ | |_ _ __ _   _
  \___ \ / __/ _ \| '_ \ / _ \  \___ \ / _ \ '_ \| __| '__| | | |
  ____) | (_| (_) | |_) |  __/  ____) |  __/ | | | |_| |  | |_| |
 |_____/ \___\___/| .__/ \___| |_____/ \___|_| |_|\__|_|   \__, |
                  | |                                       __/ |
                  |_|                                      |___/

**Comment by Autumn-27** [comment]
这个问题感觉像是 docker网络问题，我这没办法复现...

**Comment by Autumn-27** [comment]
重启一下server试试

**Comment by qzinori** [comment]
> 重启一下server试试

我是在群晖上安装的，重启了重装了也是不行

**Comment by Autumn-27** [comment]
师傅加下好友吧

**Comment by qzinori** [comment]
> 师傅加下好友吧

可以的

**Comment by qzinori** [comment]
> > 师傅加下好友吧
> 
> 可以的

wx qzinori

**Comment by laishouchao** [comment]
大佬是否解决了，我遇到相同问题，装在服务器上，本机连接都是通的，改了web的容器到同一docker网络下依旧不行

**Comment by qzinori** [comment]
看看waf的问题

**Comment by eleveni386** [comment]
我docker安装的，也遇到这个问题。
