### ISSUE TITLE
单机部署报错 ✘ Container scope-sentry         Error

### ISSUE THREAD

**Issue by laishouchao** [Autumn-27/ScopeSentry#62]
```
[root@localhost ScopeSentry]# docker-compose -f single-host-deployment.yml up -d
WARN[0000] /root/ScopeSentry/single-host-deployment.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 0/4
[+] Running 48/16                                                                                                                                                           0.2s 
 ✔ redis Pulled                                                                                                                                                           518.1s 
 ✔ scopesentry-scan Pulled                                                                                                                                               1208.5s 
 ✔ scope-sentry Pulled                                                                                                                                                    186.9s 
 ✔ mongodb Pulled                                                                                                                                                        1818.4s                                                                                                                                                         
[+] Running 5/5
 ✔ Network scopesentry-network    Created                                                                                                                                   0.1s 
 ✔ Container scopesentry-redis    Healthy                                                                                                                                  12.5s 
 ✔ Container scopesentry-mongodb  Healthy                                                                                                                                  11.7s 
 ✘ Container scope-sentry         Error                                                                                                                                    25.1s 
 ✔ Container scopesentry-scan     Created                                                                                                                                   0.0s 
dependency failed to start: container scope-sentry is unhealthy
```
logs
```
WARNING:  Current configuration will not reload as not all conditions are met, please refer to documentation.
INFO:     Started server process [26]
INFO:     Waiting for application startup.
2024-08-12 16:08:06.521 | ERROR    | core.db:create_database:152 - Error creating database: scopesentry-mongodb:27017: [Errno 113] No route to host (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 2.0s, Topology Description: <TopologyDescription id: 66b9c2e4233383cfcf13a261, topology_type: Unknown, servers: [<ServerDescription ('scopesentry-mongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('scopesentry-mongodb:27017: [Errno 113] No route to host (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
ERROR:    Traceback (most recent call last):
  File "/opt/ScopeSentry/core/db.py", line 42, in create_database
    database_names = await client.list_database_names()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1952, in list_database_names
    return [doc["name"] for doc in self.list_databases(session, nameOnly=True, comment=comment)]
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1925, in list_databases
    res = admin._retryable_read_command(cmd, session=session)
  File "/usr/local/lib/python3.7/site-packages/pymongo/database.py", line 1026, in _retryable_read_command
    return self.__client._retryable_read(_cmd, read_preference, session)
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1499, in _retryable_read
    retryable=retryable,
  File "/usr/local/lib/python3.7/site-packages/pymongo/_csot.py", line 107, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1461, in _retry_internal
    retryable=retryable,
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 2315, in run
    return self._read() if self._is_read else self._write()
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 2437, in _read
    self._server = self._get_server()
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 2401, in _get_server
    self._server_selector, self._session, address=self._address
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1303, in _select_server
    server = topology.select_server(server_selector)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 302, in select_server
    server = self._select_server(selector, server_selection_timeout, address)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 286, in _select_server
    servers = self.select_servers(selector, server_selection_timeout, address)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 237, in select_servers
    server_descriptions = self._select_servers_loop(selector, server_timeout, address)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 260, in _select_servers_loop
    f"{self._error_message(selector)}, Timeout: {timeout}s, Topology Description: {self.description!r}"
pymongo.errors.ServerSelectionTimeoutError: scopesentry-mongodb:27017: [Errno 113] No route to host (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 2.0s, Topology Description: <TopologyDescription id: 66b9c2e4233383cfcf13a261, topology_type: Unknown, servers: [<ServerDescription ('scopesentry-mongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('scopesentry-mongodb:27017: [Errno 113] No route to host (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/opt/ScopeSentry/main.py", line 107, in startup_db_client
    await db.create_database()
  File "/opt/ScopeSentry/core/db.py", line 153, in create_database
    exit(0)
  File "/usr/local/lib/python3.7/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0

ERROR:    Application startup failed. Exiting.
   _____                         _____            _              
  / ____|                       / ____|          | |             
 | (___   ___ ___  _ __   ___  | (___   ___ _ __ | |_ _ __ _   _ 
  \___ \ / __/ _ \| '_ \ / _ \  \___ \ / _ \ '_ \| __| '__| | | |
  ____) | (_| (_) | |_) |  __/  ____) |  __/ | | | |_| |  | |_| |
 |_____/ \___\___/| .__/ \___| |_____/ \___|_| |_|\__|_|   \__, |
                  | |                                       __/ |
                  |_|                                      |___/ 
Server Version: 1.4
Starting nginx: nginx.
```

**Comment by Autumn-27** [comment]
web连接不到mongo 看看是不是docker网络出问题了

**Comment by laishouchao** [comment]
排查解决了，关闭系统的防火墙和selinux，可以正常部署了




来SC
***@***.***




------------------ 原始邮件 ------------------
发件人: Rainy-Autumn ***@***.***&gt;
发送时间: 2024年8月12日 16:15
收件人: Autumn-27/ScopeSentry ***@***.***&gt;
抄送: 来SC ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Autumn-27/ScopeSentry] 单机部署报错 ✘ Container scope-sentry         Error (Issue #62)





 
web连接不到mongo 看看是不是docker网络出问题了

**Comment by laishouchao** [comment]
服务器防火墙拦截了Docker容器间流量，关闭防火墙解决问题
